# -*- coding: utf-8 -*-
"""cataract_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U0Ui3RNok_nhhR61Cl7xeKEwCtM5exeW
"""

import numpy as np
import pandas as pd
import os

from google.colab import drive
drive.mount('/content/drive')

train_dir= r"/content/drive/My Drive/cataract_dataset/train"
test_dir= r"/content/drive/My Drive/cataract_dataset/test"

#importing libraries for model training
from tensorflow.keras.applications import VGG16
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# Initialize the ImageDataGenerator with data augmentation for training
train_datagen = ImageDataGenerator(
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    rescale=1/255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

# Initialize the ImageDataGenerator for testing (without augmentation)
test_datagen = ImageDataGenerator(rescale=1./255)

# Define batch size
batch_size = 32

# Create training and testing data generators
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=batch_size,
    class_mode='binary'
)

test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(224, 224),
    batch_size=batch_size,
    class_mode='binary',
    shuffle=False
)

# Input shape since VGG16 is used
input_shape = (224, 224, 3)

# Load the base model
base_model = VGG16(weights='imagenet', include_top=False, input_shape=input_shape)

# Freeze all layers in the base model
for layer in base_model.layers:
    layer.trainable = False

# Add custom layers on top of the base model for the classification task of cataract images
model = Sequential([
    base_model,
    Flatten(),
    Dense(128, activation='relu', kernel_regularizer='l2'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

# Compile the model with an initial learning rate
model.compile(optimizer=Adam(learning_rate=0.0001), loss='binary_crossentropy', metrics=['accuracy'])

# Define callbacks
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
model_checkpoint = ModelCheckpoint('best_model_v10.keras', monitor='val_loss', save_best_only=True)

# Train the model with frozen base layers
history = model.fit(
    train_generator,
    epochs=40,
    validation_data=test_generator,
    callbacks=[early_stopping, model_checkpoint]
)

# Load the best model from training
model.load_weights('best_model_v10.keras')

# Fine-tune the model: Unfreeze the last few layers of the base model
for layer in base_model.layers[-4:]:
    layer.trainable = True

# Train model on the data again to finetune last few layers
model.compile(optimizer=Adam(learning_rate=0.0001), loss='binary_crossentropy', metrics=['accuracy'])

# Continue training with fine-tuned layers
history_fine_tuning = model.fit(
    train_generator,
    epochs=20,
    validation_data=test_generator,
    callbacks=[early_stopping, model_checkpoint]
)

# Save the final model (architecture + weights) in .keras format
final_model_dir = os.path.join('..', 'cataract_app')
if not os.path.exists(final_model_dir):
    os.makedirs(final_model_dir)

final_model_path = os.path.join(final_model_dir, 'final_model.keras')
model.save(final_model_path)

print(f"Class labels mapping: {train_generator.class_indices}")

model.evaluate(test_generator, steps=len(test_generator))

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image

def load_and_predict_image(image_path, target_size=(224, 224)):

    # Load the image from the given path
    img = image.load_img(image_path, target_size=target_size)

    # Display the image
    plt.imshow(img)
    plt.axis('off')  # Hide axis
    plt.show()

    # Preprocess the image to match model input requirements
    img_array = image.img_to_array(img)  # Convert image to array
    img_array = np.expand_dims(img_array, axis=0)  # Expand dimensions to match model input
    img_array /= 255.0  # Normalize the image (assuming the model was trained with normalized inputs)
    # Predict the class
    predictions = model.predict(img_array)

    # If softmax is used in the last layer, get the class with the highest probability
    predicted_class = np.argmax(predictions, axis=1)

    # Display the predicted class
    print(f"Predicted class: {predicted_class[0]}")

    return predicted_class[0]

image_path = "/content/drive/My Drive/cataract_dataset/test/cataract/image_265.png"
load_and_predict_image(image_path)

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.title('Training & Validation Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Training & Validation Loss')
plt.legend()
plt.show()

test_loss, test_accuracy = model.evaluate(test_generator)
print(f'Test Accuracy: {test_accuracy * 100:.2f}%')

from sklearn.metrics import classification_report, confusion_matrix

y_true = test_generator.classes
y_pred = model.predict(test_generator)
y_pred_classes = np.round(y_pred)

print(classification_report(y_true, y_pred_classes))
print(confusion_matrix(y_true, y_pred_classes))

